package conversion

import (
	"text/template"
)

var tplDialect = template.Must(template.New("").Parse(
	`// Package {{ .PkgName }} contains the {{ .PkgName }} dialect.
//
//autogenerated:yes
package {{ .PkgName }}

import (
	"github.com/merlindrones/gomavlib/pkg/message"
	"github.com/merlindrones/gomavlib/pkg/dialect"
)

// Dialect contains the dialect definition.
var Dialect = dial

// dial is not exposed directly in order not to display it in godoc.
var dial = &dialect.Dialect{
	Version: {{.Version}},
	Messages: []message.Message{
{{- range .Defs }}
	// {{ .Name }}
{{- range .Messages }}
		&Message{{ .Name }}{},
{{- end }}
{{- end }}
	},
}
`))

var tplEnum = template.Must(template.New("").Parse(
	`//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package {{ .PkgName }}

{{- if .Link }}

import (
	"github.com/merlindrones/gomavlib/pkg/dialects/{{ .Enum.DefName }}"
)

{{- range .Enum.Description }}
// {{ . }}
{{- end }}
type {{ .Enum.Name }} = {{ .Enum.DefName }}.{{ .Enum.Name }}

const (
{{- $en := .Enum }}
{{- range .Enum.Values }}
{{- range .Description }}
		// {{ . }}
{{- end }}
		{{ .Name }} {{ $en.Name }} = {{ $en.DefName }}.{{ .Name }}
{{- end }}
)

{{- else }}

import (
	"strconv"
{{- if .Enum.Bitmask }}
	"strings"
{{- end }}
	"fmt"
)

{{- range .Enum.Description }}
// {{ . }}
{{- end }}
type {{ .Enum.Name }} uint64

const (
{{- $pn := .Enum.Name }}
{{- range .Enum.Values }}
{{- range .Description }}
	// {{ . }}
{{- end }}
	{{ .Name }} {{ $pn }} = {{ .Value }}
{{- end }}
)

{{- if .Enum.Bitmask }}
var values_{{ .Enum.Name }} = []{{ .Enum.Name }}{
{{- range .Enum.Values }}
	{{ .Name }},
{{- end }}
}
{{- end }}

var value_to_label_{{ .Enum.Name }} = map[{{ .Enum.Name }}]string{
{{- range .Enum.Values }}
	{{ .Name }}: "{{ .Name }}",
{{- end }}
}

var label_to_value_{{ .Enum.Name }} = map[string]{{ .Enum.Name }}{
{{- range .Enum.Values }}
	"{{ .Name }}": {{ .Name }},
{{- end }}
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e {{ .Enum.Name }}) MarshalText() ([]byte, error) {
{{- if .Enum.Bitmask }}
	if e == 0 {
		return []byte("0"), nil
	}
	var names []string
	for _, val := range values_{{ .Enum.Name }} {
		if e&val == val {
			names = append(names, value_to_label_{{ .Enum.Name }}[val])
		}
	}
	return []byte(strings.Join(names, " | ")), nil
{{- else }}
	if name, ok := value_to_label_{{ .Enum.Name }}[e]; ok {
		return []byte(name), nil
	}
	return []byte(strconv.Itoa(int(e))), nil
{{- end }}
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *{{ .Enum.Name }}) UnmarshalText(text []byte) error {
{{- if .Enum.Bitmask }}
	labels := strings.Split(string(text), " | ")
	var mask {{ .Enum.Name }}
	for _, label := range labels {
		if value, ok := label_to_value_{{ .Enum.Name }}[label]; ok {
			mask |= value
		} else if value, err := strconv.Atoi(label); err == nil {
			mask |= {{ .Enum.Name }}(value)
		} else {
			return fmt.Errorf("invalid label '%s'", label)
		}
	}
	*e = mask
{{- else }}
	if value, ok := label_to_value_{{ .Enum.Name }}[string(text)]; ok {
	   *e = value
	} else if value, err := strconv.Atoi(string(text)); err == nil {
	   *e = {{ .Enum.Name }}(value)
	} else {
		return fmt.Errorf("invalid label '%s'", text)
	}
{{- end }}
	return nil
}

// String implements the fmt.Stringer interface.
func (e {{ .Enum.Name }}) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
{{- end }}
`))

var tplMessage = template.Must(template.New("").Parse(
	`//autogenerated:yes
//nolint:revive,misspell,govet,lll
package {{ .PkgName }}

{{- if .Link }}

import (
	"github.com/merlindrones/gomavlib/pkg/dialects/{{ .Msg.DefName }}"
)

{{- range .Msg.Description }}
// {{ . }}
{{- end }}
type Message{{ .Msg.Name }} = {{ .Msg.DefName }}.Message{{ .Msg.Name }}

{{- else }}

{{- range .Msg.Description }}
// {{ . }}
{{- end }}
type Message{{ .Msg.Name }} struct {
{{- range .Msg.Fields }}
{{- range .Description }}
	// {{ . }}
{{- end }}
	{{ .Line }}
{{- end }}
}

// GetID implements the message.Message interface.
func (*Message{{ .Msg.Name }}) GetID() uint32 {
	return {{ .Msg.ID }}
}

{{- end }}
`))
