//autogenerated:yes
//nolint:revive
package common

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/merlindrones/gomavlib/pkg/dialect"
)

func TestDialect(t *testing.T) {
	_, err := dialect.NewReadWriter(Dialect)
	require.NoError(t, err)
}
