//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_SERIAL_CONTROL_FLAG(t *testing.T) {
	var e SERIAL_CONTROL_FLAG
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
