//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_REBOOT_SHUTDOWN_ACTION(t *testing.T) {
	var e REBOOT_SHUTDOWN_ACTION
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
