//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_MAV_ODID_CLASS_EU(t *testing.T) {
	var e MAV_ODID_CLASS_EU
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
