//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_MOTOR_TEST_ORDER(t *testing.T) {
	var e MOTOR_TEST_ORDER
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
