//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_VTOL_TRANSITION_HEADING(t *testing.T) {
	var e VTOL_TRANSITION_HEADING
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
