//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_PREFLIGHT_STORAGE_MISSION_ACTION(t *testing.T) {
	var e PREFLIGHT_STORAGE_MISSION_ACTION
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
