//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_ESC_CONNECTION_TYPE(t *testing.T) {
	var e ESC_CONNECTION_TYPE
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
