//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_CELLULAR_NETWORK_FAILED_REASON(t *testing.T) {
	var e CELLULAR_NETWORK_FAILED_REASON
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
