//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_MAV_SENSOR_ORIENTATION(t *testing.T) {
	var e MAV_SENSOR_ORIENTATION
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
