//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_ORBIT_YAW_BEHAVIOUR(t *testing.T) {
	var e ORBIT_YAW_BEHAVIOUR
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
