//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_MAV_BATTERY_CHARGE_STATE(t *testing.T) {
	var e MAV_BATTERY_CHARGE_STATE
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
