//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_WIFI_CONFIG_AP_MODE(t *testing.T) {
	var e WIFI_CONFIG_AP_MODE
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
