//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_NAV_VTOL_LAND_OPTIONS(t *testing.T) {
	var e NAV_VTOL_LAND_OPTIONS
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
