//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_POSITION_TARGET_TYPEMASK(t *testing.T) {
	var e POSITION_TARGET_TYPEMASK
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
