//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_MAV_EVENT_CURRENT_SEQUENCE_FLAGS(t *testing.T) {
	var e MAV_EVENT_CURRENT_SEQUENCE_FLAGS
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
