//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_CAMERA_TRACKING_TARGET_DATA(t *testing.T) {
	var e CAMERA_TRACKING_TARGET_DATA
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
