//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_MAV_SYS_STATUS_SENSOR_EXTENDED(t *testing.T) {
	var e MAV_SYS_STATUS_SENSOR_EXTENDED
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
