//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_ACTUATOR_CONFIGURATION(t *testing.T) {
	var e ACTUATOR_CONFIGURATION
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
