//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_COMPUTER_STATUS_FLAGS(t *testing.T) {
	var e COMPUTER_STATUS_FLAGS
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
