//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_RTK_BASELINE_COORDINATE_SYSTEM(t *testing.T) {
	var e RTK_BASELINE_COORDINATE_SYSTEM
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
