//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_VIDEO_STREAM_ENCODING(t *testing.T) {
	var e VIDEO_STREAM_ENCODING
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
