//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_UAVCAN_NODE_MODE(t *testing.T) {
	var e UAVCAN_NODE_MODE
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
