//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_HIGHRES_IMU_UPDATED_FLAGS(t *testing.T) {
	var e HIGHRES_IMU_UPDATED_FLAGS
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
