//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_GIMBAL_DEVICE_CAP_FLAGS(t *testing.T) {
	var e GIMBAL_DEVICE_CAP_FLAGS
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
