//autogenerated:yes
//nolint:revive,misspell,govet,lll
package common

import (
	"github.com/merlindrones/gomavlib/pkg/dialects/standard"
)

// Version and capability of autopilot software. This should be emitted in response to a request with MAV_CMD_REQUEST_MESSAGE.
type MessageAutopilotVersion = standard.MessageAutopilotVersion
