//autogenerated:yes
//nolint:revive,govet,errcheck
package minimal

import (
	"testing"
)

func TestEnum_MAV_MODE_FLAG_DECODE_POSITION(t *testing.T) {
	var e MAV_MODE_FLAG_DECODE_POSITION
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
