//autogenerated:yes
//nolint:revive,govet,errcheck
package standard

import (
	"testing"
)

func TestEnum_MAV_BOOL(t *testing.T) {
	var e MAV_BOOL
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
