//autogenerated:yes
//nolint:revive,govet,errcheck
package standard

import (
	"testing"
)

func TestEnum_FIRMWARE_VERSION_TYPE(t *testing.T) {
	var e FIRMWARE_VERSION_TYPE
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
