//autogenerated:yes
//nolint:revive,govet,errcheck
package standard

import (
	"testing"
)

func TestEnum_MAV_BOOL(t *testing.T) {
	var e MAV_BOOL
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
