//autogenerated:yes
//nolint:revive,govet,errcheck
package standard

import (
	"testing"
)

func TestEnum_FIRMWARE_VERSION_TYPE(t *testing.T) {
	var e FIRMWARE_VERSION_TYPE
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
