//autogenerated:yes
//nolint:revive,govet,errcheck
package standard

import (
	"testing"
)

func TestEnum_MAV_PROTOCOL_CAPABILITY(t *testing.T) {
	var e MAV_PROTOCOL_CAPABILITY
	_ = e.UnmarshalText([]byte{})
	_, _ = e.MarshalText()
	_ = e.String()
}
